spring:
  datasource:
    #url: jdbc:mysql://mysql:3306/microservices?serverTimezone=CET&createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/allegro?serverTimezone=CET&createDatabaseIfNotExist=true
    username: root
    password: Wiking94
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        messages:
          basename: messages/messages




server:
  port: 8080

